title: Felipe Ferrão's page
description: Hello! My name is Felipe and I'm a postdoctoral associate at the University of Florida, working under Patricio Munoz. I obtained my Ph.D. in Genetics and Plant Breeding at the University of São Paulo (ESALQ,USP), Brazil. 
I am currently interested in Bayesian applications for next-generation sequencing data. 
#show_downloads: true
google_analytics:
theme: jekyll-theme-architect



