title: Felipe Ferrão
logo: picture.png
description: Horticultural Science Department - IFAS; University of Florida; 2211 Fifield Hall Off 2211;Gainesville, FL 32603
**email:** lfelipe [dot] ferrao [at] gmail [dot] com
#show_downloads: true
google_analytics:
theme:  jekyll-theme-minimal



