title: Felipe Ferrão
description: I'm a postdoctoral associate at the University of Florida, working under Patricio Munoz. I obtained my Ph.D. in Genetics and Plant Breeding at the University of São Paulo (ESALQ,USP), Brazil. I am currently interested in Statistical Genetics
#show_downloads: true
google_analytics:
theme: jekyll-theme-architect



